### PR TITLE
Starting to use some options for enabling/disabling the compilation of parts of the library

### PR DESCRIPTION
**Pull request by piponazo**
This is just a proposal for adding some options to the boost package so a developer can decide which boost libraries to use. Note that I did not add all the existing libraries since first I want to be sure whether you like this idea. If you are happy with this change, I will complete the PR.

In my personal project I only use those libraries and I do not want to spend time compiling things that we do not need. Actually this could be also interesting when the disk space is a limited resource and you have to have several boost packages for different platforms. 

I do not like the part in which I have to check every different option to add a new flag. I am wondering if there is a better approach in python to make that piece of code smaller and cleaner. Note that I am not a python developer 😋 

Note that if all the options are **False**, then all the boost libraries are compiled.

### CODE REVIEW

**Comment by lasote** [comment]
Hi, sorry for the delay, crazy days! I totally like the idea, you can keep working on it. 
You can simplify the code doing something like this (not tested, just the idea):

```
option_names = {
       self.options.with_date_time: "with_date_time",
       self.options.with_filesystem: "with_filesystem",
       self.options.with_iostreams: "with_iostreams",
...
}

for option, option_name in option_names.values():
    if option:
        flags.append(option_name)
        specific_libs = True # use _ underscore instead of camel case

```

Thanks!!!

**Comment by piponazo** [comment]
I updated the PR with all the changes. Now we have options for each specific boost library and I am using the dictionary as you proposed.

Since the test_package is only depending on boost::regex I added that default option in the test/conanfile.py. I am not sure if this will cause problems with the travis CI, since now the command **conan test_package** will only compile the regex library.

**Comment by lasote** [comment]
Hi @piponazo, first of all great work. But there is a problem with the options set to false. I would like to keep the actual behavior, if someone do not specify any option it should install all the libraries. I think it's the main use case. Also I would like to keep the current conan packages SHAs, it can be guaranteed adding only "false" defaulted options, so adding a new option do not alter the package SHA. It's ok in your PR but it won't compile any library but regex. 

The test_package is not really important, it's only to guarantee a minimum packaging test, the really important thing is that if someone do not specify any option it has to compile every library, otherwise we will break all the user's projects where they are using this Boost recipe.

I think the best way to do it is to change the options to "without_xxx" defaulted to false. In your case I understand it could be annoying, because if you only want 1 library you need to specify a lot of options to False, but as I said, I don't want to break the compatibility.

What do you think? It's ok for you?

Thanks @piponazo

**Comment by piponazo** [comment]
Hi @lasote. I understand your concern. I think that I already tried that and when all the "with-XXX" options are false, the **b2** command compiles all the libraries.

The major issue that I found with **b2** is that we cannot mix --with-XXX options and ---without-XXX options. 

In principle, if you say that adding new options with default values to False should not be a problem for the SHAs, everything should be fine. Note that all the options are defaulted to False in the conanbuild.py file of the conan recipe. I only enable the regex option inside the test folder.

Anyway, I will double check when I have some time ;)

**Comment by lasote** [comment]
Yeah, You are right, by default should compile all, but if b2 is complaining about mixing with and without... maybe with the current python option we have a problem. What if we always use "--without-xxx" b2 options? This way all variables are False defaulted, it still have sense with default builds (no activated options means all compiled). The problem is that you need to specify a lot of "--without-xxx" if you only use a couple of boost libraries, but I think it is not so bad.

**Comment by piponazo** [comment]
I'm fine with that, that approach will be more robust. I will update the PR whenever I have some spare time ;)

**Comment by piponazo** [comment]
I am closing this PR and I will create another one with a cleaner history ;)

**Pull request closed without merging**
