### PR TITLE
Correct whitespace problem in command & mix between build_type and runtime

### PR DESCRIPTION
**Pull request by dkgs**

### CODE REVIEW

**Comment by dkgs** [comment]
Also add correction on wether add the debug tag on libs name as stated here : https://github.com/conan-io/conan/issues/681

The "g" tag should not depend on MDd or MTd but on the build type.

**Comment by dkgs** [comment]
Whoopps sorry for the closing/opening still not used to git :)
I also should have done two pull requests... I'll do better next time.

**Comment by lasote** [comment]
Hi @dkgs, about the name change `Boost_USE_DEBUG_RUNTIME` to `Boost_USE_DEBUG_TAG`, I don't want to change anything from the `OriginalFindBoost*` files, there are copied from CMake installations. 
About the comparison with `compiler.runtime`, What's the problem? Any bug detected? Any build failing? Compare with Debug flag is a different thing, because in Linux and OSX you don't have compiler.runtime but you have `build_type`.
About the quotes in the command line :+1: 

Thanks!

**Comment by dkgs** [comment]
@lasote Yes, I encountered the problem when building in Debug mode with MD in release (even though it was a mistake) : the error was that the boost library was not found because it was named with a "g" and CMake didn't care to search it with a "g" because MD was used (hence the comparison with build_type instead of compiler.runtime).

For the difference between Windows & Linux, the "g" is added by CMake only on Windows, so there is no risk on this side.

About the name change, from `Boost_USE_DEBUG_RUNTIME` to `Boost_USE_DEBUG_TAG`, well I just found it more appropriate as the "g" is present wether you link to MD or MDd or MT or MTd. But if it is present in the original CMake installation, then it goes against the conclusion a read here : https://github.com/conan-io/conan/issues/681 because in this case the Debug build would be associated with a debug runtime.

**Comment by lasote** [comment]
Ok, so let's keep `Boost_USE_DEBUG_RUNTIME` name to keep intact the original and update the PR to see if it broke something.

**Comment by lasote** [comment]
You still have changes in OriginalFindBoost* files

**Comment by dkgs** [comment]
done :) I'm editing directly in Github, so I have to do it file by file ^^

**Comment by dkgs** [comment]
Oww, @lasote AppVeyor didn't pass because `CONAN_CURRENT_PAGE=28` & `CONAN_CURRENT_PAGE=30` failed due to a remote connection failure, is it possible to just relaunch them ?

**Comment by lasote** [comment]
@dkgs not needed. I'm merging it. THANKS! :dancer:

**Pull request merged**
