### PR TITLE
Refine FindBoost wrapper

### PR DESCRIPTION
**Pull request by jason2506**
I just reviewed the FindBoost wrapper and made some (breaking) changes:

- Separate original `FindBoost.cmake` and Conan FindBoost wrapper.
- Update original `FindBoost.cmake` to latest released version [(source)](https://github.com/Kitware/CMake/blob/release/Modules/FindBoost.cmake).
- Remove `SET(Boost_DEBUG 0)`. I think it would be better to be specified by client code.
- Just use original `FindBoost.cmake` to import header-only libraries.
- **[Breaking Change]** `find_package(Boost)` without specifying `COMPONENTS` should only import header-only libraries (compatible with behavior of original `FindBoost.cmake`).

The reason for the breaking change is that, as a user of Conan/CMake, I don't expect conan-boost version of `find_package(Boost)` has different behavior than the original one. In addition, it would not make sense to import everything by default if some of `without_*` package options to be `True`.

### CODE REVIEW

**Comment by lasote** [comment]
@jason2506 it's a great job, thank you very much. I agree with you about keeping the same CMake behavior. If we break someone's packages they can link against CONAN_LIBS directly.
I'm going to review some details but it looks very good.

**Comment by bilke** [comment]
This does not work with CMake `< 3.4` as the `OriginalFindBoost.cmake` requires that the `string`-command has a `APPEND`-subcommand.

```bash
-- ********* Conan FindBoost wrapper **********
COMPONENTS TO SEARCH: 
CMake Error at /home/travis/.conan/data/Boost/1.60.0/lasote/stable/package/b012e82ee33e6839e6408a203ec6f06d061050e3/OriginalFindBoost.cmake:1183 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  /home/travis/.conan/data/Boost/1.60.0/lasote/stable/package/b012e82ee33e6839e6408a203ec6f06d061050e3/FindBoost.cmake:39 (include)
  ...
```

In general I think there should not be original CMake find package files included as they often depend on certain CMake minimum versions.

**Comment by lasote** [comment]
@bilke thanks for notice. You are right, I have to find a best approach.

**Comment by lasote** [comment]
I've opened a PR #30 that choose between 2 different findCmake versions depending on the current CMake version. I've tested it and it seems to be ok, let's see the CI

**Comment by lasote** [comment]
@bilke I've pushed and uploaded the new recipe, should be compatible but until CI publish all the binary packages (about 12 hours) you'll need to build from sources. Tell me if there is any problem.

Thanks guys!

**Comment by bilke** [comment]
Thank you very much @lasote for the fast fix. Our project is happily building again!

**Pull request merged**
