### PR TITLE
v1.64.0 (fixes #11, #7)

### LINKED ISSUE #11: 1.61.0 is out
http://www.boost.org/users/history/version_1_61_0.html

### PR DESCRIPTION
**Pull request by Croydon**
This PR
 * provides Boost v1.64.0
 * updates Zlib to v1.2.11
 * adds support for Visual Studio 2017
 * makes sure, that
   * when GCC and Clang are installed, and we want to use Clang, we actually do that also for the bootstrap part
     * before GCC was used for bootstrapping, then Clang for main step
   * when several GCC or Clang versions are installed, we actually use now the version specified, no more missmatches

@lasote Could you please use the rebase + merge strategy for further pull requests? Merge commits leave a bad commit history which isn't very helpful.

Also as a follow up you might like to edit the readme to point to Bintray and add GCC 6.3/GCC 7.1/Clang 3.8/Clang 3.9/Clang 4.0 support to the CI.

### CODE REVIEW

**Comment by Croydon** [comment]
@lasote Ping?

**Comment by lasote** [comment]
Hi, thanks for the PR. Reviewing the Boost recipe is a TODO task that requires some effort and we have to find it. As you well said, it has to be pointed to the conan-center, but we would like some support from the Boost community for that. Also, I would like to remove the findBoost.cmake mechanism and get it working with the official one.
I will check with @memsharded if we can get some time and take some decisions.

**Comment by lasote** [comment]
Also to include to conan-center first we need to include bzip2

**Comment by Croydon** [comment]
Since I got asked about it, you all can find the recipe together with several packages from our CI uploaded here: https://bintray.com/inexorgame/inexor-conan/Boost%3Alasote

**Comment by solvingj** [comment]
@Croydon's repository only includes builds with boost:shared=false and only compiler.runtime=MT .  It also did not include the logic for building from source, which I understand is non-trivial. 

@lasote Is it possible to get this merged with the boostrapping for boost build and deployed to conan-transit while you discuss conan-center ?  It needs to go there first anyway.

**Comment by lasote** [comment]
I'm merging this to the testing/1.64.0. There are still pending issues and things to change before I can publish this recipe anywhere.

**Comment by lasote** [comment]
Uploaded packages in conan-community repository:
https://bintray.com/conan-community/conan/Boost%3Aconan

I had to do some changes like the toolchain name for linux and I got rid of the custom findBoost for CMake, just renaming the libraries when the name contains `-sgd-` and removing the prefix `lib` with static libraries makes CMake original findBoost to find the conan packages by itself.

Please take a look to the changes and try the package.

**Comment by Croydon** [comment]
@lasote https://github.com/inexorgame/conan-boost/compare/release/1.64.0-pr...lasote:release/1.64.0?expand=1#diff-2b1d42f71f22b7ea0412d7602dec166fR159

Why did you remove the NOT here? Having only the major version as a parameter is relevant for the original GCC on Linux, now it seems to only apply for MinGW for which I personally don't even know how the version number is handled.

This change seems to reintroduce the problem that when several GCC versions are installed parallel the default one is getting used instead of the version specified for/in Conan.

**Comment by lasote** [comment]
Passing only the major version makes it fails in Linux. You can take a look here:

https://travis-ci.org/lasote/conan-boost/jobs/265872327

`error: toolset gcc initialization:
error: version '4' requested but 'g++-4' not found and version '4.9.2' of default 'g++' does not match
error: initialized from`

> This change seems to reintroduce the problem that when several GCC versions are installed parallel the default one is getting used instead of the version specified for/in Conan.

Sorry but I don't remember if we talked about this problem. Please @grafikrobot and @solvingj, we need some help with this.

**Comment by Croydon** [comment]
> Passing only the major version makes it fails in Linux.

It works for us for GCC5, GCC6 and GCC7. Our project doesn't support GCC 4 or even older, so we don't run tests for that.
https://travis-ci.org/inexorgame/ci-prebuilds/jobs/266872262#L1868

> The only workable solution is to set in the user-config.jam or in project-config.jam the full path to the compiler executable (or just the name if the exec is in the PATH). 

This is nasty and not an acceptable solution for us.

Maybe there is a difference in the version handling/gcc finding between GCC4 and GCC5? 

Taking a look your own CI jobs seem to proof this:
https://travis-ci.org/lasote/conan-boost/jobs/265872335#L1801

It works with GCC >= 5. So we should probably add a 

if LINUX AND GCC > 5 then 
  only major version 
else 
  entire version passing

**Comment by Croydon** [comment]
Starting with GCC5 the major version is the only one which matters. 
https://gcc.gnu.org/develop.html#num_scheme

And again b2 works fine with gcc-5, gcc-6 and gcc-7 parameters, in our/inexorgame's setup as well as in lasote's CI setup.

We only need to add another AND GCC > 5 check if not then entire version parsing.
Then it should work for all GCC versions without forcing all consumers to use workarounds and without that b2 chooses the default gcc version against anyones will.

**Comment by Croydon** [comment]
In addition: as I worked on updating this recipe I started to parse the entire GCC version for GCC version > 5 and it failed.

**Comment by lasote** [comment]
@Croydon Sure, we could add the `if self.settings.compiler == "gcc" and self.settings.compiler.version >= "5"` to pass the full version. 
But I don't understand your last comment, you tried and it didn't work?

**Comment by Croydon** [comment]
> But I don't understand your last comment, you tried and it didn't work?

What works: Giving b2 a parameter like gcc-5, gcc6 and gcc-7 as I suggested, what DOES NOT work was giving it a parameter as gcc-6.2.

This is was I suggest:
https://github.com/inexorgame/conan-boost/commit/4a382cff6a1e33458bb6b9d5aa0e14bfad2b211d

and it is successfully tested on GCC >= 5, Clang >= 3.8 and Visual Studio >= 2015

https://travis-ci.org/inexorgame/ci-prebuilds/builds/266972992
https://ci.appveyor.com/project/inexor-game/ci-prebuilds/build/0.82 (first job is a time out)

This patch should also work now successfully with GCC < 5.

**Comment by lasote** [comment]
Thanks for your help @Croydon.
Patched and running CI: 
https://travis-ci.org/lasote/conan-boost/builds/267206150
https://ci.appveyor.com/project/lasote/conan-boost/build/1.0.145

**Pull request merged**
