### PR TITLE
Minimal support for cross-compiling for ARM

### PR DESCRIPTION
**Pull request by DavidZemon**
Previously, the recipe assumed that we were compiling for either x86 or x86_64. There's a lot more logic that needs to go into this to support all the different ABIs and binary formats, but this was at least a start that should support most ARM platforms.

### CODE REVIEW

**Comment by lasote** [comment]
Many thanks! I've to review some other things and will go back to this PR. Looks very good!

**Comment by lasote** [comment]
I have a question, if you are cross building to ARM how you managed to boostrap and build the bjam dependency for the native system if you were specifying settings for a cross system?

**Comment by DavidZemon** [comment]
Uh... I'm not sure. I didn't think about that. I didn't touch the bootstrap function at all, so I guess it was already ignoring the `self.settings.os` and `self.settings.arch` parameters and using whatever default compiler it could find?

**Comment by lasote** [comment]
yeah, the thing is, the compiler that finds is the CC, CXX, so it builds the build system to run on the host machine, and of course it fails. I tried with an Android profile I have pointing to a standalone toolchain, I didn't expect to work, but the bootstrap part surprised me.

**Comment by DavidZemon** [comment]
Well... the bootstrap method might need fixing. I'm really unsure. I've never messed with Boost's build system at all until this pull request. Do you think the `./bootstrap.sh --with-toolset=....` should be receiving the same `toolset` argument as that which is computed in the `get_build_flags()` method?

**Comment by theirix** [comment]
Sorry for hijacking tread. If you will refactor a toolset detection, please take a look for a `toolset` option to override toolset flag because even complex `get_build_flags` cannot deduce correct platform for complex cases (i.e. devtoolset in #51).

**Comment by lasote** [comment]
First of all many thanks for your contribution and your help. I have a problem, the CI for the 1.64 is pretty broken, and I cannot verify well if these changes are good. 
I'm working (a lot) on the 1.66 recipe, it required many work to get a green build (stil wip), I'll try to introduce your changes there. Would be ok if you open a PR to the 1.66 when all is ready?

**Comment by lasote** [comment]
I created the release/1.66.0 introducing all this ideas you purpose. Thanks so much, as I told you I mentioned you in the readme. Please, if any thing could be improved, open a PR again.

**Comment by DavidZemon** [comment]
You actually have great timing on this. At the end of the day Friday, I finally finished a Conanifying a bunch of projects at work and was able to produce something that is demo-able for the rest of the team. With that done, I can get back to cleaning up some of the rough edges that I left, including this Boost thing. I'll take a look at 1.66.0 and see how that works compared to my fork of 1.64.0. Thanks!

**Pull request closed without merging**
